### PR TITLE
FIX: Redundant babel-runtime dependency. Closes react-pdf#670

### PR DESCRIPTION
**Pull request by knoopx**

### CODE REVIEW

**Comment by saimonmoore** [comment]
@diegomura could you please publish a new version with this fix? 🙏 

We're also having to patch-package our way around this bug 😢

**Comment by knoopx** [comment]
@saimonmoore and others reaching this, this simpler workaround works if you are using webpack:

```
    resolve: {
      alias: {
        // fix: @reactpdf/textkit redundant dependency on babel-runtime
        "babel-runtime": "@babel/runtime",
      },
```

**Comment by saimonmoore** [comment]
@knoopx how did you workaround this? :)

**Comment by saimonmoore** [comment]
Yeah I tried that already :). Our internal platform is doing more funky things so that alone didn't cut it for us ;)

**Comment by diegomura** [comment]
Sorry I missed this!! Merging and publishing new version today

**Comment by diegomura** [comment]
Just published 0.4.1 including this change. Thanks!

**Comment by saimonmoore** [comment]
Awesome. Thanks @diegomura 👏

**Pull request merged**
